<a href="https://colab.research.google.com/github/gurleenk01/python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])

In [3]:
arr[1:4]

array([2, 3, 4])

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [9]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [10]:
np.random.rand(5)

array([0.66179039, 0.95403964, 0.73192639, 0.61518909, 0.83121827])

In [11]:
np.random.randn(5)

array([-0.49602689,  1.47204725,  1.17072162,  0.08959282, -1.24644135])

In [13]:
np.sum(arr)

15

In [14]:
np.random.randint(1,100)

58

In [15]:
arr=np.arange(25)

In [16]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
arr.argmax()

24

In [18]:
arr.argmin()

0

In [19]:
arr.dtype

dtype('int64')

In [20]:
arr>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [22]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24])

In [23]:
arr=np.arange(0,6)

In [24]:
arr+arr

array([ 0,  2,  4,  6,  8, 10])

In [25]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [26]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [27]:
arr**2

array([ 0,  1,  4,  9, 16, 25])

In [28]:
np.var(arr)

2.9166666666666665

In [30]:
np.mean(arr)

2.5

In [31]:
np.unique(arr)

array([0, 1, 2, 3, 4, 5])